fx_version 'cerulean'
game 'gta5'
description 'Simple, Standalone and Open-Source blip creator (github.com/nwvh/wx_blips)'
author 'woox <wx#5352>'
version '1.1.0'
lua54 'yes'
client_script 'client/*'
shared_script 'configs/blips_config.lua'
